/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPancake, IPancakeInterface } from "../IPancake";

const _abi = [
  {
    inputs: [],
    name: "getReserves",
    outputs: [
      {
        internalType: "uint112",
        name: "_reserve0",
        type: "uint112",
      },
      {
        internalType: "uint112",
        name: "_reserve1",
        type: "uint112",
      },
      {
        internalType: "uint32",
        name: "_blockTimestampLast",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPancake__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeInterface {
    return new utils.Interface(_abi) as IPancakeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPancake {
    return new Contract(address, _abi, signerOrProvider) as IPancake;
  }
}
