/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IUniswap, IUniswapInterface } from "../IUniswap";

const _abi = [
  {
    inputs: [],
    name: "_blockTimestamp",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUniswap__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapInterface {
    return new utils.Interface(_abi) as IUniswapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniswap {
    return new Contract(address, _abi, signerOrProvider) as IUniswap;
  }
}
